### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by EmmanuelTobi** [keleog/bbc_pidgin_scraper#1]
Would be interesting hosting this and creating API endpoints, I'm considering building an application around it. with flutter or Kotlin.

what do you feel about this?

**Comment by keleog** [comment]
That would be nice! Please let me know what you need from me whenever you are ready. :)

**Comment by EmmanuelTobi** [comment]
Alright, I should be ready mid this new week. By them I hope API endpoints should be ready so get me well started to build.

**Comment by EmmanuelTobi** [comment]
Alright, I should be ready mid this new week. By then, I hope API endpoints should be ready to get me well started to build.

**Comment by EmmanuelTobi** [comment]
Also, any plans for image urls? Probably getting only the top used image if the article has any.

**Comment by keleog** [comment]
None for now cos I am majorly interested in the text data. A PR to that effect is welcome though.
